name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  workflowId:
    required: true
    description: 'the workflow id (you can pass the name of the workflow file)'
  runId:
    required: true
    description: 'the run id (pass $ {{ github.run_id }})'
  GITHUB_TOKEN:
    required: true
    description: 'the github token (pass $ {{ secrets.GITHUB_TOKEN }})'
runs:
  using: 'node12'
  main: 'dist/index.js'
